name:               "Stranger Things SparkCore"
description:        "Stranger Things lights driven by SparkCore"

url:                ""
author:             "konahart"
email:              "laurel.elise.hart@gmail.com"
twitter:            "konahart"
github:             "konahart/Stranger-Things-SparkCore"

disqus_shortname:   "konahart"

background:         "http://i.imgur.com/kA73HiU.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            "/Stranger-Things-SparkCore"
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "Demos"
    href:           "/demos"
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "https://github.com/konahart/Stranger-Things-SparkCore"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
