name:               "Stranger Things SparkCore"
description:        "Stranger Things lights driven by SparkCore"

url:                "konahart.com/Stranger-Things-SparkCore"
author:             "konahart"
email:              "laurel.elise.hart@gmail.com"
twitter:            "konahart"
github:             "konahart"

disqus_shortname:   "konahart"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
